### ISSUE TITLE
Microsoft.Windows.AppNotifications missing

### ISSUE THREAD

**Issue by mimi89999** [pywinrt/python-winsdk#35]
Hello,

I wanted to use https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.appnotifications.builder.appnotificationbuilder?view=windows-app-sdk-1.2 as described in https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/app-notifications/app-notifications-quickstart?tabs=cpp, but it seems like there are no bindings for it in `python-winsdk`.

**Comment by dlech** [comment]
Can you use toasts instead?

I would eventually like to enable more APIs but compilers not named clang are already struggling to compile everything so we need to break things up into individual packages first (#1).

**Comment by dlech** [comment]
fixed by https://github.com/pywinrt/pywinrt/pull/30
