### ISSUE TITLE
Request to add binding for CreateForWindow or GetWindowIdFromWindow

### ISSUE THREAD

**Issue by Avasam** [pywinrt/python-winsdk#5]
https://docs.microsoft.com/en-us/windows/win32/api/windows.graphics.capture.interop/nf-windows-graphics-capture-interop-igraphicscaptureiteminterop-createforwindow

CreateForWindow is used to create a CaptureGraphicsItem form an HWND. But it seems the binding it missing from this project.

While doable, being forced to use the CaptureGraphicsPicker would complicated things a lot for us since we use a custom Picker that works across all other capture methods.

**Comment by dlech** [comment]
Can you give an example of how one would use this? 

Does `InitializeWithWindow` work instead? We already have this at `winsdk._winrt.initailze_with_window()`. If not, we could consider adding a similar `create_for_window()` function. It isn't clear what the output type of that function is though.

**Comment by dlech** [comment]
If there is a way to get a WindowId from an HWIND, maybe https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscaptureitem.trycreatefromwindowid would work instead.

**Comment by Avasam** [comment]
From what I saw, going from a HWND to a WindowId, and then using `TryCreateFromWindowId` should work as well.
Either way is fine by me. `GetWindowIdFromWindow` was the other option I was looking at and would also satisfy me.

**Comment by dlech** [comment]
I think it will work to just cast the HWND to WindowId.

```python
item = GraphicsCaptureItem.try_create_from_window_id(WindowId(hwnd))
```

**Comment by Avasam** [comment]
```py
window_id = WindowId(hwnd)
item = GraphicsCaptureItem.try_create_from_window_id(window_id.value)
autosplit.windows_graphics_capture = __create_and_start_graphics_capture_session(item)
```
Good idea, but results in
```
    item = GraphicsCaptureItem.try_create_from_window_id(window_id)

OSError: [WinError -2147467262] No such interface supported
```

which is a different error then just passing the `hwnd` or `window_id.value` to `try_create_from_window_id`: `OSError: [WinError -2147024809] The parameter is incorrect`

**Comment by dlech** [comment]
I also read that not all windows can be captured. For example, I tried to capture a turtle (tkinter) window and it doesn't work. But then I tried using an hwnd from a VS Code window and it worked.

**Comment by Avasam** [comment]
I've only been trying with windows that the GraphicsPicker also sees:
![image](https://user-images.githubusercontent.com/1350584/162657136-3a60b29a-6fd4-483d-9172-7f4182a4e0a1.png)

I've been trying with the HWND of a few different windows as well to make sure, always the same result.

**Comment by dlech** [comment]
Can you give a full working example to reproduce these errors?

**Comment by Avasam** [comment]
> Can you give a full working example to reproduce these errors?

```py
from traceback import print_exception

import win32gui
from winsdk.windows.graphics.capture import GraphicsCaptureItem
from winsdk.windows.ui import WindowId


def print_hwnd_win32gui(hwnd, _):
    window_text = win32gui.GetWindowText(hwnd)
    if (
        window_text
        and window_text not in ("Default IME", "MSCTFIME UI")
        and "Window" not in window_text
    ):
        print(type(hwnd), hwnd, window_text)


win32gui.EnumWindows(print_hwnd_win32gui, '')


while True:
    try:
        hwnd = int(input("^ Enter an HWND from above ^ :"))
    except:
        print("not an int")
        continue

    try:
        print("Selected window:", win32gui.GetWindowText(hwnd))
    except:
        print("not a valid HWND")
        continue

    try:  # OSError: [WinError -2147024809] The parameter is incorrect
        item = GraphicsCaptureItem.try_create_from_window_id(hwnd)  # Error here
    except OSError as exception:
        print_exception(OSError, exception, None)

    try:  # OSError: [WinError -2147467262] No such interface supported
        window_id = WindowId(hwnd)
        item = GraphicsCaptureItem.try_create_from_window_id(window_id)  # Error here
    except OSError as exception:
        print_exception(OSError, exception, None)
```

**Comment by dlech** [comment]
> ```python
>     try:  # OSError: [WinError -2147024809] The parameter is incorrect
>         item = GraphicsCaptureItem.try_create_from_window_id(hwnd)  # Error here
> ```

This is expected since `hwind` is `int` is not `WindowId`.

> ```python
> 
>     try:  # OSError: [WinError -2147467262] No such interface supported
>         window_id = WindowId(hwnd)
>         item = GraphicsCaptureItem.try_create_from_window_id(window_id)  # Error here
> ```

I do not get an error here. 

Maybe your Windows version is too old? I have Windows 11 (build 22000). This API was introduced in build 20348.

https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscaptureitem.trycreatefromwindowid?view=winrt-22000

**Comment by Avasam** [comment]
`Version	10.0.19044 Build 19044`, which as far as I know, is the latest Windows 10 version.
Yeah that'd do it. It works fine on my Windows 11 (22000) machine as well.

More reasons to want a binding for `GetWindowIdFromWindow` (build 1809 ) for Windows 10 support.

**Comment by dlech** [comment]
> More reasons to want a binding for `GetWindowIdFromWindow` (since version 1809) for Windows 10 support.

`GetWindowIdFromWindow` is part of the "Windows App SDK" which is not the regular Windows SDK, so it would required users to install the Windows App runtime. I would rather not add this dependency. Also, it wouldn't help anyway since it only gets us the `WindowId` which requires the missing `try_create_from_window_id()` API.

**Comment by dlech** [comment]
Thanks for the research. I've added a new `interop` submodule so now it should be possible to do this:

```python
from winsdk.windows.graphics.capture.interop import create_for_monitor, create_for_window

# replace with create_for_window(hwnd) as needed
item = create_for_monitor(0)
print(item.display_name)
```

**Comment by Avasam** [comment]
> Thanks for the research. I've added a new `interop` submodule so now it should be possible to do this:
> 
> ```python
> from winsdk.windows.graphics.capture.interop import create_for_monitor, create_for_window
> 
> # replace with create_for_window(hwnd) as needed
> item = create_for_monitor(0)
> print(item.display_name)
> ```

It works! A huge thanks to you for your continued support. This will make a lot of our app's users happy to have a more compatible screen capture option than BitBlt.
