### ISSUE TITLE
Pyright/Pylance : Some types are potentially unknown

### ISSUE THREAD

**Issue by Avasam** [pywinrt/python-winsdk#8]
This happens with all `_ns_module.*` types as far as I can tell, but here's an example from `windows.graphics.directx.direct3d11.__init__.py`:
![image](https://user-images.githubusercontent.com/1350584/162583110-d7470106-c48f-4618-b507-d4e074073773.png)

Then in `windows.graphics.capture.__init__.pyi`
![image](https://user-images.githubusercontent.com/1350584/162583141-37df84dc-aef8-4993-bf42-8622d0ac30fa.png)

Which produces strict type-checking errors in my code, unless I explicitly specify the type:
![image](https://user-images.githubusercontent.com/1350584/162583253-481c71f0-2800-4e5f-af70-ad922dee4310.png)

Even though `IDirect3DSurface` is defined in `windows.graphics.directx.direct3d11.__init__.pyi`:
![image](https://user-images.githubusercontent.com/1350584/162583476-3f23719f-8d4b-45cd-baff-2056bd9bd3d9.png)

I don't think this is expected behavior from python-winsdk (it doesn't seem like it). Nor do I know *why* it's happening or how to fix it. I can raise an issue over at Pyright if you can't correct this issue and believe it's on their side.

**Comment by dlech** [comment]
It sounds like Pylance has changed since last time I used it (which was probably a few months ago). It is probably worth asking there how to handle "weird" imports like this. For example, are there some kind of comments or type hints we can add to tell it to only look at the `.pyi` files for certain modules?

There are also some typing fixes I haven't released yet - although I don't think they will help in this case.

**Comment by dlech** [comment]
I think I found the issue. `winsdk.windows.graphics.capture` imports `winsdk.windows.ui.composition` but this module isn't available for technical reasons. This is what introduces the `Unknown` to all of the typings in the file.

I think we can fix it by changing the imports to something like:

```python
import winsdk.windows.foundation as _winsdk_windows_foundation
```

**Comment by dlech** [comment]
Probably could still be considered a bug in Pylance though.

**Comment by Avasam** [comment]
I can confirm that changing the import to `import winsdk.windows.ui.composition as _winsdk_windows_ui_composition` in the pyi file only and `    def create_from_visual(visual: _winsdk_windows_ui_composition.Visual) -> GraphicsCaptureItem: ...`
Does fix it
![image](https://user-images.githubusercontent.com/1350584/162600494-374f2fa7-ff2b-477a-ad7c-c9844ef7b3f4.png)

**Comment by Avasam** [comment]
Even `from winsdk.windows.ui import composition` then `composition.Visual` seems to work (not sure if there's other side effects.
I guess as long as you don't use `winsdk.windows.ui.composition.<something>` directly in the type definition.

**Comment by dlech** [comment]
Let's see if we can get it fixed in Pyright first.

**Comment by Avasam** [comment]
https://github.com/microsoft/pyright/issues/3328#issuecomment-1097547290

https://github.com/microsoft/pyright/releases/tag/1.1.237

> Bug Fix: Fixed bug that resulted in incorrect type evaluation when an import statement failed to resolve and targeted a submodule of a previous import statement, such as import a.b followed by import a.b.c where a.b.c couldn't be resolved. In this circumstance, pyright "forgot" that a.b had been resolved previously, so all symbols imported from a.b were evaluated as Unknown.
